spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hdc?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
logging:
  level:
    sql: debug